version: '2'
services:
  application:
    build:
      context: ./application
      args:
        UID: ${UID}
    container_name: egghead-redux-application
    image: egghead-redux-application-image
    ports:
      - 8080:8080
    volumes:
      - ./application:/home/node/application